Repository mwaskom/seaborn, pull requests merged in 2022-09, with the labels that each got.

#2989 Add tutorial page for Mark properties with cross-referencing from relevant docstrings
  doc/_tutorial/properties.ipynb
  doc/conf.py
  doc/tutorial.rst
  seaborn/_core/plot.py
  seaborn/_marks/area.py
  seaborn/_marks/bar.py
  seaborn/_marks/base.py
  seaborn/_marks/dot.py
  seaborn/_marks/line.py
Labels: docs

#2991 Create tutorial index programmatically and update some content
  doc/.gitignore
  doc/Makefile
  doc/_tutorial/categorical.ipynb
  doc/_tutorial/error_bars.ipynb
  doc/_tutorial/regression.ipynb
  doc/_tutorial/relational.ipynb
  doc/conf.py
  doc/requirements.txt
  doc/sphinxext/tutorial_builder.py
  doc/tutorial.rst
  doc/tutorial.yaml
Labels: docs

#2995 Update the single-letter color codes as part of the Plot theme context
  seaborn/_core/plot.py
  tests/_marks/test_area.py
  tests/_marks/test_bar.py
  tests/_marks/test_dot.py
Labels: themes, objects-plot

#2993 Add tutorial for objects interface and remove 'nextgen' preview
  doc/_docstrings/objects.Band.ipynb
  doc/_docstrings/objects.Bar.ipynb
  doc/_docstrings/objects.Bars.ipynb
  doc/_docstrings/objects.Dot.ipynb
  doc/_docstrings/objects.Path.ipynb
  doc/_tutorial/objects_interface.ipynb
  doc/installing.rst
  doc/nextgen/.gitignore
  doc/nextgen/Makefile
  doc/nextgen/api.rst
  doc/nextgen/conf.py
  doc/nextgen/demo.ipynb
  doc/nextgen/index.ipynb
  doc/nextgen/index.rst
  doc/nextgen/nb_to_doc.py
  doc/sphinxext/tutorial_builder.py
  doc/tutorial.yaml
Labels: docs

#2996 Rename layout parameter algo->engine
  doc/_docstrings/objects.Plot.layout.ipynb
  doc/_tutorial/properties.ipynb
  seaborn/_compat.py
  seaborn/_core/plot.py
  tests/_core/test_plot.py
Labels: api, objects-plot

#2997 Assorted pre-release doc tweaks
  doc/_static/css/custom.css
  doc/_tutorial/objects_interface.ipynb
  doc/_tutorial/regression.ipynb
  doc/api.rst
  doc/conf.py
  doc/index.rst
  doc/sphinxext/tutorial_builder.py
  doc/whatsnew/v0.12.0.rst
Labels: docs

#2998 Add FAQ page to docs
  doc/_tutorial/function_overview.ipynb
  doc/_tutorial/regression.ipynb
  doc/faq.rst
  doc/index.rst
Labels: docs

#2999 Update errorbar API in example gallery and add new strip/reg example
  examples/anscombes_quartet.py
  examples/grouped_barplot.py
  examples/jitter_stripplot.py
  examples/pointplot_anova.py
  examples/strip_regplot.py
Labels: docs

#3009 Use pip extras for installation of dev tools
  .github/workflows/ci.yaml
  README.md
  ci/utils.txt
  doc/README.md
  doc/requirements.txt
  pyproject.toml
Labels: infrastructure

#2963 Add pre-commit hook config
  .pre-commit-config.yaml
  README.md
  ci/deps_pinned.txt
  ci/getmsfonts.sh
  doc/README.md
  doc/_static/copybutton.js
  doc/_templates/autosummary/base.rst
  doc/_templates/autosummary/object.rst
  doc/citing.rst
  doc/faq.rst
  doc/index.rst
  doc/tutorial.yaml
  doc/whatsnew/v0.11.0.rst
  doc/whatsnew/v0.11.1.rst
  doc/whatsnew/v0.2.0.rst
  doc/whatsnew/v0.7.0.rst
  licences/NUMPYDOC_LICENSE
  pyproject.toml
  seaborn/external/docscrape.py
  tests/test_utils.py
Labels: infrastructure

#3010 Fix: Make PolyFit stat robust to missing data
  doc/whatsnew/v0.12.1.rst
  seaborn/_stats/regression.py
  tests/_stats/test_regression.py
Labels: bugfix, objects-stat

#3011 Silence various warnings in test suite
  tests/test_categorical.py
  tests/test_distributions.py
  tests/test_regression.py
  tests/test_relational.py
Labels: testing

#3013 CI: Add biweekly scheduled run to detect changes in environment or dependencies
  .github/workflows/ci.yaml
Labels: testing, infrastructure

#3014 CI: Impove dataset caching and build docs in parallel
  .github/workflows/ci.yaml
  ci/cache_datasets.py
  ci/cache_test_datasets.py
  doc/Makefile
Labels: testing, infrastructure

#3018 Parallelize sphinx in CI build
  .github/workflows/ci.yaml
Labels: infrastructure

#3020 CI: Improve example dataset usage
  .github/workflows/ci.yaml
  doc/_docstrings/clustermap.ipynb
  doc/_docstrings/heatmap.ipynb
  doc/_docstrings/lmplot.ipynb
  doc/_docstrings/regplot.ipynb
  doc/_docstrings/residplot.ipynb
  seaborn/matrix.py
  seaborn/regression.py
Labels: testing, infrastructure

#3031 errorbar doc patched
  seaborn/categorical.py
Labels: docs, mod:categorical

#3039 CI: Make tests more robust to concurrency
  tests/_core/test_plot.py
  tests/_marks/test_area.py
  tests/_marks/test_bar.py
  tests/_marks/test_dot.py
  tests/_marks/test_line.py
  tests/conftest.py
  tests/test_core.py
  tests/test_rcmod.py
Labels: testing

#3040 Update pandas syntax to avoid deprecated behavior
  seaborn/categorical.py
  seaborn/distributions.py
  tests/_stats/test_histogram.py
  tests/test_categorical.py
Labels: upstream, internals

#3044 Typing: use pandas-type-stubs and address arising issues
  pyproject.toml
  seaborn/_core/data.py
  seaborn/_core/groupby.py
  seaborn/_core/plot.py
  seaborn/_core/rules.py
  seaborn/_core/scales.py
  seaborn/_core/typing.py
  seaborn/_stats/aggregation.py
Labels: testing
