Repository mwaskom/seaborn, pull requests merged in 2023-08, with the labels that each got.

#3436 Hash-pin GitHub Actions
  .github/workflows/ci.yaml
Labels: infrastructure

#3440 Generalize internal scaling operation
  seaborn/_base.py
  seaborn/categorical.py
  seaborn/distributions.py
  seaborn/relational.py
  tests/test_base.py
  tests/test_categorical.py
Labels: plots, needs-release-note

#3369 Support polars and other data libraries via dataframe interchange
  seaborn/_base.py
  seaborn/_core/data.py
  seaborn/_core/plot.py
  seaborn/_core/typing.py
  seaborn/axisgrid.py
  seaborn/categorical.py
  seaborn/distributions.py
  tests/_core/test_data.py
  tests/_core/test_plot.py
  tests/conftest.py
  tests/test_axisgrid.py
  tests/test_base.py
Labels: api, objects-core, needs-release-note

#3445 Add log_scale to categorical plots
  seaborn/_base.py
  seaborn/categorical.py
  seaborn/distributions.py
  tests/test_base.py
  tests/test_categorical.py
Labels: enhancement, mod:categorical, needs-release-note

#3447 Squash a large number of warnings in the tests
  pyproject.toml
  seaborn/_base.py
  seaborn/_core/plot.py
  seaborn/_core/properties.py
  seaborn/_stats/counting.py
  seaborn/categorical.py
  seaborn/distributions.py
  tests/_stats/test_density.py
  tests/conftest.py
  tests/test_categorical.py
  tests/test_distributions.py
Labels: testing, internals

#3449 Simplify some Plotter class method/attributes that haven't proven useful
  seaborn/_base.py
  seaborn/_decorators.py
  seaborn/_marks/base.py
  seaborn/axisgrid.py
  seaborn/categorical.py
  seaborn/distributions.py
  seaborn/matrix.py
  seaborn/miscplot.py
  seaborn/palettes.py
  seaborn/relational.py
  tests/test_base.py
  tests/test_decorators.py
Labels: internals

#3400 Change get_linestyle to get_dashes for Collections
  tests/_marks/test_line.py
Labels: upstream

#3451 Ignore units= in relplot with kind='scatter'
  seaborn/relational.py
  tests/test_relational.py
Labels: mod:relational, ux

#3452 Deprecate accepting an array-typed palette, which is not intentional
  seaborn/_base.py
  tests/test_base.py
Labels: ux, needs-release-note

#3453 Fail early with a nice message when statsmodels is needed
  seaborn/regression.py
  tests/test_regression.py
Labels: ux

#3454 Allow move_legend to overwrite the labels
  seaborn/utils.py
  tests/test_utils.py
Labels: needs-release-note
